/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated.categorias'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated.configuracion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedMovimientosRouteImport } from './routes/_authenticated.movimientos'
import { Route as AuthenticatedNuevoProductoRouteImport } from './routes/_authenticated.nuevo-producto'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated.productos'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated.reportes'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated.stock'
import { Route as AuthenticatedTransferenciasRouteImport } from './routes/_authenticated.transferencias'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated.ventas'
import { Route as AuthenticatedEditarProductoIdRouteImport } from './routes/_authenticated.editar-producto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovimientosRoute =
  AuthenticatedMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNuevoProductoRoute =
  AuthenticatedNuevoProductoRouteImport.update({
    id: '/nuevo-producto',
    path: '/nuevo-producto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransferenciasRoute =
  AuthenticatedTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditarProductoIdRoute =
  AuthenticatedEditarProductoIdRouteImport.update({
    id: '/editar-producto/$id',
    path: '/editar-producto/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/nuevo-producto': typeof AuthenticatedNuevoProductoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/editar-producto/$id': typeof AuthenticatedEditarProductoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/nuevo-producto': typeof AuthenticatedNuevoProductoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/editar-producto/$id': typeof AuthenticatedEditarProductoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/movimientos': typeof AuthenticatedMovimientosRoute
  '/_authenticated/nuevo-producto': typeof AuthenticatedNuevoProductoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/transferencias': typeof AuthenticatedTransferenciasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
  '/_authenticated/editar-producto/$id': typeof AuthenticatedEditarProductoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracion'
    | '/dashboard'
    | '/movimientos'
    | '/nuevo-producto'
    | '/perfil'
    | '/productos'
    | '/reportes'
    | '/stock'
    | '/transferencias'
    | '/usuarios'
    | '/ventas'
    | '/editar-producto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracion'
    | '/dashboard'
    | '/movimientos'
    | '/nuevo-producto'
    | '/perfil'
    | '/productos'
    | '/reportes'
    | '/stock'
    | '/transferencias'
    | '/usuarios'
    | '/ventas'
    | '/editar-producto/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/categorias'
    | '/_authenticated/configuracion'
    | '/_authenticated/dashboard'
    | '/_authenticated/movimientos'
    | '/_authenticated/nuevo-producto'
    | '/_authenticated/perfil'
    | '/_authenticated/productos'
    | '/_authenticated/reportes'
    | '/_authenticated/stock'
    | '/_authenticated/transferencias'
    | '/_authenticated/usuarios'
    | '/_authenticated/ventas'
    | '/_authenticated/editar-producto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movimientos': {
      id: '/_authenticated/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AuthenticatedMovimientosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nuevo-producto': {
      id: '/_authenticated/nuevo-producto'
      path: '/nuevo-producto'
      fullPath: '/nuevo-producto'
      preLoaderRoute: typeof AuthenticatedNuevoProductoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transferencias': {
      id: '/_authenticated/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof AuthenticatedTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editar-producto/$id': {
      id: '/_authenticated/editar-producto/$id'
      path: '/editar-producto/$id'
      fullPath: '/editar-producto/$id'
      preLoaderRoute: typeof AuthenticatedEditarProductoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMovimientosRoute: typeof AuthenticatedMovimientosRoute
  AuthenticatedNuevoProductoRoute: typeof AuthenticatedNuevoProductoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTransferenciasRoute: typeof AuthenticatedTransferenciasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
  AuthenticatedEditarProductoIdRoute: typeof AuthenticatedEditarProductoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMovimientosRoute: AuthenticatedMovimientosRoute,
  AuthenticatedNuevoProductoRoute: AuthenticatedNuevoProductoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTransferenciasRoute: AuthenticatedTransferenciasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
  AuthenticatedEditarProductoIdRoute: AuthenticatedEditarProductoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
